#!/bin/bash

CLI_CRATES="log clap glob"
PET_CRATES="roxmltree cssparser"
VIS_CRATES="piet kurbo piet-cairo cairo-rs png"
TOY_CRATES="minifb"

for proj in cli pet vis toy ; do
    CRATES=${proj^^}_CRATES
    for crate in ${!CRATES} ; do
        echo -n "$crate = "
        grep -m 1 "$crate = " ${proj}/Cargo.toml | cut -z -d\" -f2
        echo -n " -> "
        cargo search --limit 1 $crate | head -1 | awk '{print $3}'
    done
done
