[package]

name = "ascetic_vis"
version = "0.0.1-pre"
description = "Graphical rendering of c-e structures"
authors = ["k7f"]
edition = "2018"
license = "MIT"
repository = "https://github.com/k7f/ascetic"
readme = "README.md"

[dependencies]

piet = "0.0.9"
kurbo = "0.5"
piet-cairo = "0.0.9"
cairo-rs = "0.8"
png = "0.16"
